sudo: false
dist: trusty
language: c

addons:
  apt:
    packages:
    - build-essential
    - git
    - gcc-arm-none-eabi
    - libnewlib-arm-none-eabi

script:
  - make -C vendor/libopencm3
  - make
  - make -C firmware
  - make -C bootloader
  - make -C demo

notifications:
  webhooks:
    urls:
      - http://sway.gk2.sk:5000/travis
      - http://163.172.132.178:5000/travis
    on_success: always
    on_failure: always
    on_start: always
